-- =============================================
-- HablaFácil AAC - Complete Words Seed Data
-- Generated from vocabulary.json (179 words)
-- Run on Supabase branch: refactor-categories-words-symbols
-- =============================================
SET search_path = public;
-- Insert/Update all vocabulary words
INSERT INTO public.words (id, spanish, english, category, frequency, symbol_url) VALUES
  ('yo', 'Yo', 'I', 'pronombres', 3, '/symbols/yo.svg'),
  ('tu', 'Tú', 'You', 'pronombres', 3, 'https://api.arasaac.org/api/pictograms/6625?download=false'),
  ('el', 'Él', 'He', 'pronombres', 3, 'https://api.arasaac.org/api/pictograms/6480?download=false'),
  ('ella', 'Ella', 'She', 'pronombres', 3, 'https://api.arasaac.org/api/pictograms/7028?download=false'),
  ('nosotros', 'Nosotros', 'We', 'pronombres', 3, 'https://api.arasaac.org/api/pictograms/7185?download=false'),
  ('ellos', 'Ellos', 'They', 'pronombres', 3, 'https://api.arasaac.org/api/pictograms/7032?download=false'),
  ('esto', 'Esto', 'This', 'pronombres', 3, 'https://api.arasaac.org/api/pictograms/7095?download=false'),
  ('eso', 'Eso', 'That', 'pronombres', 3, 'https://api.arasaac.org/api/pictograms/6906?download=false'),
  ('todo', 'Todo', 'Everything', 'pronombres', 3, 'https://api.arasaac.org/api/pictograms/5596?download=false'),
  ('nada', 'Nada', 'Nothing', 'pronombres', 3, 'https://api.arasaac.org/api/pictograms/29839?download=false'),
  ('mi', 'Mío', 'Mine', 'pronombres', 3, 'https://api.arasaac.org/api/pictograms/12264?download=false'),
  ('quien', 'Quién', 'Who', 'pronombres', 3, '/symbols/quien.svg'),
  ('que', 'Qué', 'What', 'pronombres', 3, '/symbols/que.svg'),
  ('donde', 'Dónde', 'Where', 'pronombres', 3, '/symbols/donde.svg'),
  ('cuando', 'Cuándo', 'When', 'pronombres', 3, '/symbols/cuando.svg'),
  ('porque', 'Por qué', 'Why', 'pronombres', 3, 'https://api.arasaac.org/api/pictograms/36719?download=false'),
  ('quiero', 'Quiero', 'want', 'verbos', 3, '/symbols/quiero.svg'),
  ('necesito', 'Necesito', 'need', 'verbos', 3, '/symbols/necesito.svg'),
  ('tengo', 'Tengo', 'have', 'verbos', 3, 'https://api.arasaac.org/api/pictograms/32761?download=false'),
  ('me_gusta', 'Me gusta', 'like', 'verbos', 3, 'https://api.arasaac.org/api/pictograms/37826?download=false'),
  ('no_me_gusta', 'No me gusta', 'dislike', 'verbos', 3, 'https://api.arasaac.org/api/pictograms/37825?download=false'),
  ('puedo', 'Puedo', 'can', 'verbos', 3, '/symbols/puedo.svg'),
  ('quieres', 'Quieres', 'you want', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/5441?download=false'),
  ('quiere', 'Quiere', 'wants', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/5441?download=false'),
  ('queremos', 'Queremos', 'we want', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/5441?download=false'),
  ('quieren', 'Quieren', 'they want', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/5441?download=false'),
  ('necesitas', 'Necesitas', 'you need', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/37160?download=false'),
  ('necesita', 'Necesita', 'needs', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/37160?download=false'),
  ('necesitamos', 'Necesitamos', 'we need', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/37160?download=false'),
  ('necesitan', 'Necesitan', 'they need', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/37160?download=false'),
  ('tienes', 'Tienes', 'you have', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/32761?download=false'),
  ('tiene', 'Tiene', 'has', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/32761?download=false'),
  ('tenemos', 'Tenemos', 'we have', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/32761?download=false'),
  ('tienen', 'Tienen', 'they have', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/32761?download=false'),
  ('puedes', 'Puedes', 'you can', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/6544?download=false'),
  ('puede', 'Puede', 'can', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/6544?download=false'),
  ('podemos', 'Podemos', 'we can', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/6544?download=false'),
  ('pueden', 'Pueden', 'they can', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/6544?download=false'),
  ('te_gusta', 'Te gusta', 'you like', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/37825?download=false'),
  ('le_gusta', 'Le gusta', 'likes', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/37825?download=false'),
  ('nos_gusta', 'Nos gusta', 'we like', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/37825?download=false'),
  ('les_gusta', 'Les gusta', 'they like', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/37825?download=false'),
  ('ir', 'Ir', 'go', 'verbos', 3, 'https://api.arasaac.org/api/pictograms/8142?download=false'),
  ('comer', 'Comer', 'eat', 'verbos', 3, '/symbols/comer.svg'),
  ('beber', 'Beber', 'drink', 'verbos', 3, '/symbols/beber.svg'),
  ('jugar', 'Jugar', 'play', 'verbos', 3, '/symbols/jugar.svg'),
  ('dormir', 'Dormir', 'sleep', 'verbos', 3, '/symbols/dormir.svg'),
  ('ayudar', 'Ayudar', 'help', 'verbos', 3, '/symbols/ayudar.svg'),
  ('hablar', 'Hablar', 'talk', 'verbos', 3, '/symbols/hablar.svg'),
  ('escuchar', 'Escuchar', 'listen', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/6572?download=false'),
  ('ver', 'Ver', 'see', 'verbos', 3, '/symbols/ver.svg'),
  ('leer', 'Leer', 'read', 'verbos', 2, '/symbols/leer.svg'),
  ('escribir', 'Escribir', 'write', 'verbos', 2, '/symbols/escribir.svg'),
  ('caminar', 'Caminar', 'walk', 'verbos', 2, '/symbols/caminar.svg'),
  ('correr', 'Correr', 'run', 'verbos', 2, '/symbols/correr.svg'),
  ('sentarse', 'Sentarse', 'sit', 'verbos', 2, '/symbols/sentarse.svg'),
  ('levantarse', 'Levantarse', 'stand up', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/13370?download=false'),
  ('esperar', 'Esperar', 'wait', 'verbos', 2, '/symbols/esperar.svg'),
  ('terminar', 'Terminar', 'finish', 'verbos', 2, '/symbols/terminar.svg'),
  ('empezar', 'Empezar', 'start', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/5431?download=false'),
  ('abrir', 'Abrir', 'open', 'verbos', 2, '/symbols/abrir.svg'),
  ('cerrar', 'Cerrar', 'close', 'verbos', 2, '/symbols/cerrar.svg'),
  ('comprar', 'Comprar', 'buy', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/8986?download=false'),
  ('pagar', 'Pagar', 'pay', 'verbos', 2, 'https://api.arasaac.org/api/pictograms/6457?download=false'),
  ('si', 'Sí', 'Yes', 'sociales', 3, 'https://api.arasaac.org/api/pictograms/5584?download=false'),
  ('no', 'No', 'No', 'sociales', 3, 'https://api.arasaac.org/api/pictograms/5526?download=false'),
  ('hola', 'Hola', 'Hello', 'sociales', 3, '/symbols/hola.svg'),
  ('adios', 'Adiós', 'Goodbye', 'sociales', 3, 'https://api.arasaac.org/api/pictograms/6028?download=false'),
  ('gracias', 'Gracias', 'Thank you', 'sociales', 3, 'https://api.arasaac.org/api/pictograms/8129?download=false'),
  ('por_favor', 'Por favor', 'Please', 'sociales', 3, 'https://api.arasaac.org/api/pictograms/8195?download=false'),
  ('lo_siento', 'Lo siento', 'sorry', 'sociales', 3, 'https://api.arasaac.org/api/pictograms/11625?download=false'),
  ('perdon', 'Perdón', 'excuse me', 'sociales', 3, 'https://api.arasaac.org/api/pictograms/6285?download=false'),
  ('buenos_dias', 'Buenos días', 'Good morning', 'sociales', 2, 'https://api.arasaac.org/api/pictograms/6944?download=false'),
  ('buenas_noches', 'Buenas noches', 'Good night', 'sociales', 2, 'https://api.arasaac.org/api/pictograms/6942?download=false'),
  ('que_pregunta', '¿Qué?', 'What question', 'preguntas', 3, 'https://api.arasaac.org/api/pictograms/9853?download=false'),
  ('donde_pregunta', '¿Dónde?', 'Where question', 'preguntas', 3, 'https://api.arasaac.org/api/pictograms/7764?download=false'),
  ('cuando_pregunta', '¿Cuándo?', 'When question', 'preguntas', 3, 'https://api.arasaac.org/api/pictograms/32874?download=false'),
  ('quien_pregunta', '¿Quién?', 'Who question', 'preguntas', 3, 'https://api.arasaac.org/api/pictograms/6438?download=false'),
  ('por_que', '¿Por qué?', 'Why question', 'preguntas', 3, '/symbols/por_que.svg'),
  ('como', '¿Cómo?', 'How question', 'preguntas', 3, '/symbols/como.svg'),
  ('cuanto', '¿Cuánto?', 'How much', 'preguntas', 2, 'https://api.arasaac.org/api/pictograms/7073?download=false'),
  ('agua', 'Agua', 'Water', 'sustantivos', 3, '/symbols/agua.svg'),
  ('comida', 'Comida', 'Food', 'sustantivos', 3, '/symbols/comida.svg'),
  ('bano', 'Baño', 'Bathroom', 'sustantivos', 3, 'https://api.arasaac.org/api/pictograms/5921?download=false'),
  ('mama', 'Mamá', 'Mom', 'sustantivos', 3, 'https://api.arasaac.org/api/pictograms/2458?download=false'),
  ('papa', 'Papá', 'Dad', 'sustantivos', 3, '/symbols/papa.svg'),
  ('hermano', 'Hermano', 'Brother', 'sustantivos', 2, '/symbols/hermano.svg'),
  ('hermana', 'Hermana', 'Sister', 'sustantivos', 2, '/symbols/hermana.svg'),
  ('amigo', 'Amigo', 'Friend', 'sustantivos', 3, 'https://api.arasaac.org/api/pictograms/25790?download=false'),
  ('maestro', 'Maestro', 'Teacher', 'sustantivos', 3, '/symbols/maestro.svg'),
  ('doctor', 'Doctor', 'Doctor', 'sustantivos', 3, '/symbols/doctor.svg'),
  ('libro', 'Libro', 'Book', 'sustantivos', 2, '/symbols/libro.svg'),
  ('juguete', 'Juguete', 'Toy', 'sustantivos', 2, '/symbols/juguete.svg'),
  ('pelota', 'Pelota', 'Ball', 'sustantivos', 2, '/symbols/pelota.svg'),
  ('telefono', 'Teléfono', 'Phone', 'sustantivos', 2, '/symbols/telefono.svg'),
  ('television', 'Televisión', 'TV', 'sustantivos', 2, 'https://api.arasaac.org/api/pictograms/25498?download=false'),
  ('musica', 'Música', 'Music', 'sustantivos', 2, '/symbols/musica.svg'),
  ('carro', 'Carro', 'Car', 'sustantivos', 2, '/symbols/carro.svg'),
  ('ropa', 'Ropa', 'Clothes', 'sustantivos', 2, '/symbols/ropa.svg'),
  ('zapatos', 'Zapatos', 'Shoes', 'sustantivos', 2, 'https://api.arasaac.org/api/pictograms/2775?download=false'),
  ('medicina', 'Medicina', 'Medicine', 'sustantivos', 2, '/symbols/medicina.svg'),
  ('dolor', 'Dolor', 'Pain', 'sustantivos', 3, 'https://api.arasaac.org/api/pictograms/2367?download=false'),
  ('dinero', 'Dinero', 'Money', 'sustantivos', 2, '/symbols/dinero.svg'),
  ('caja', 'Caja', 'Cashier', 'sustantivos', 1, 'https://api.arasaac.org/api/pictograms/3001?download=false'),
  ('menu', 'Menú', 'Menu', 'sustantivos', 2, '/symbols/menu.svg'),
  ('mesa', 'Mesa', 'Table', 'sustantivos', 2, '/symbols/mesa.svg'),
  ('silla', 'Silla', 'Chair', 'sustantivos', 2, '/symbols/silla.svg'),
  ('columpio', 'Columpio', 'Swing', 'sustantivos', 2, '/symbols/columpio.svg'),
  ('resbaladilla', 'Resbaladilla', 'Slide', 'sustantivos', 2, '/symbols/resbaladilla.svg'),
  ('arbol', 'Árbol', 'Tree', 'sustantivos', 1, '/symbols/arbol.svg'),
  ('flor', 'Flor', 'Flower', 'sustantivos', 1, '/symbols/flor.svg'),
  ('lapiz', 'Lápiz', 'Pencil', 'sustantivos', 2, '/symbols/lapiz.svg'),
  ('papel', 'Papel', 'Paper', 'sustantivos', 2, '/symbols/papel.svg'),
  ('mochila', 'Mochila', 'Backpack', 'sustantivos', 2, 'https://api.arasaac.org/api/pictograms/2475?download=false'),
  ('clase', 'Clase', 'Class', 'sustantivos', 3, '/symbols/clase.svg'),
  ('recreo', 'Recreo', 'Recess', 'sustantivos', 3, 'https://api.arasaac.org/api/pictograms/27339?download=false'),
  ('tarea', 'Tarea', 'Homework', 'sustantivos', 2, 'https://api.arasaac.org/api/pictograms/11228?download=false'),
  ('almuerzo', 'Almuerzo', 'Lunch', 'sustantivos', 3, '/symbols/almuerzo.svg'),
  ('desayuno', 'Desayuno', 'Breakfast', 'sustantivos', 2, '/symbols/desayuno.svg'),
  ('cena', 'Cena', 'Dinner', 'sustantivos', 2, '/symbols/cena.svg'),
  ('cama', 'Cama', 'Bed', 'sustantivos', 2, '/symbols/cama.svg'),
  ('cocina_lugar', 'Cocina', 'Kitchen', 'sustantivos', 2, 'https://api.arasaac.org/api/pictograms/10752?download=false'),
  ('sala', 'Sala', 'Living room', 'sustantivos', 2, 'https://api.arasaac.org/api/pictograms/6211?download=false'),
  ('cuarto', 'Cuarto', 'Room', 'sustantivos', 2, '/symbols/cuarto.svg'),
  ('cabeza', 'Cabeza', 'Head', 'sustantivos', 2, '/symbols/cabeza.svg'),
  ('estomago', 'Estómago', 'Stomach', 'sustantivos', 2, '/symbols/estomago.svg'),
  ('mano', 'Mano', 'Hand', 'sustantivos', 2, '/symbols/mano.svg'),
  ('pie', 'Pie', 'Foot', 'sustantivos', 2, '/symbols/pie.svg'),
  ('feliz', 'Feliz', 'Happy', 'emociones', 3, '/symbols/feliz.svg'),
  ('triste', 'Triste', 'Sad', 'emociones', 3, '/symbols/triste.svg'),
  ('enojado', 'Enojado', 'Angry', 'emociones', 3, '/symbols/enojado.svg'),
  ('cansado', 'Cansado', 'Tired', 'emociones', 3, 'https://api.arasaac.org/api/pictograms/35537?download=false'),
  ('hambre', 'Tengo hambre', 'hungry', 'emociones', 3, 'https://api.arasaac.org/api/pictograms/4962?download=false'),
  ('sed', 'Tengo sed', 'thirsty', 'emociones', 3, 'https://api.arasaac.org/api/pictograms/4963?download=false'),
  ('frio_emocion', 'Tengo frío', 'cold feeling', 'emociones', 2, 'https://api.arasaac.org/api/pictograms/35557?download=false'),
  ('calor', 'Tengo calor', 'hot feeling', 'emociones', 2, 'https://api.arasaac.org/api/pictograms/35561?download=false'),
  ('asustado', 'Asustado', 'Scared', 'emociones', 2, 'https://api.arasaac.org/api/pictograms/35535?download=false'),
  ('sorprendido', 'Sorprendido', 'Surprised', 'emociones', 1, '/symbols/sorprendido.svg'),
  ('me_duele', 'Me duele', 'pain', 'emociones', 3, 'https://api.arasaac.org/api/pictograms/2367?download=false'),
  ('grande', 'Grande', 'Big', 'adjetivos', 3, '/symbols/grande.svg'),
  ('pequeno', 'Pequeño', 'Small', 'adjetivos', 3, 'https://api.arasaac.org/api/pictograms/4716?download=false'),
  ('mas', 'Más', 'More', 'adjetivos', 3, '/symbols/mas.svg'),
  ('menos', 'Menos', 'Less', 'adjetivos', 2, 'https://api.arasaac.org/api/pictograms/5512?download=false'),
  ('bueno', 'Bueno', 'Good', 'adjetivos', 3, '/symbols/bueno.svg'),
  ('malo', 'Malo', 'Bad', 'adjetivos', 3, '/symbols/malo.svg'),
  ('nuevo', 'Nuevo', 'New', 'adjetivos', 2, '/symbols/nuevo.svg'),
  ('viejo', 'Viejo', 'Old', 'adjetivos', 2, '/symbols/viejo.svg'),
  ('rapido', 'Rápido', 'Fast', 'adjetivos', 2, '/symbols/rapido.svg'),
  ('lento', 'Lento', 'Slow', 'adjetivos', 2, 'https://api.arasaac.org/api/pictograms/4676?download=false'),
  ('aqui', 'Aquí', 'Here', 'adjetivos', 3, 'https://api.arasaac.org/api/pictograms/5382?download=false'),
  ('alla', 'Allá', 'There', 'adjetivos', 3, 'https://api.arasaac.org/api/pictograms/5375?download=false'),
  ('arriba', 'Arriba', 'Up', 'adjetivos', 2, '/symbols/arriba.svg'),
  ('abajo', 'Abajo', 'Down', 'adjetivos', 2, '/symbols/abajo.svg'),
  ('dentro', 'Dentro', 'Inside', 'adjetivos', 2, '/symbols/dentro.svg'),
  ('fuera', 'Fuera', 'Outside', 'adjetivos', 2, '/symbols/fuera.svg'),
  ('otra_vez', 'Otra vez', 'Again', 'adjetivos', 3, 'https://api.arasaac.org/api/pictograms/37163?download=false'),
  ('diferente', 'Diferente', 'Different', 'adjetivos', 2, 'https://api.arasaac.org/api/pictograms/4628?download=false'),
  ('mismo', 'Mismo', 'Same', 'adjetivos', 2, '/symbols/mismo.svg'),
  ('uno', 'Uno', 'One', 'numeros', 3, '/symbols/uno.svg'),
  ('dos', 'Dos', 'Two', 'numeros', 3, '/symbols/dos.svg'),
  ('tres', 'Tres', 'Three', 'numeros', 3, '/symbols/tres.svg'),
  ('cuatro', 'Cuatro', 'Four', 'numeros', 2, '/symbols/cuatro.svg'),
  ('cinco', 'Cinco', 'Five', 'numeros', 2, '/symbols/cinco.svg'),
  ('diez', 'Diez', 'Ten', 'numeros', 2, '/symbols/diez.svg'),
  ('rojo', 'Rojo', 'Red', 'colores', 2, '/symbols/rojo.svg'),
  ('azul', 'Azul', 'Blue', 'colores', 2, '/symbols/azul.svg'),
  ('verde', 'Verde', 'Green', 'colores', 2, '/symbols/verde.svg'),
  ('amarillo', 'Amarillo', 'Yellow', 'colores', 2, '/symbols/amarillo.svg'),
  ('negro', 'Negro', 'Black', 'colores', 2, '/symbols/negro.svg'),
  ('blanco', 'Blanco', 'White', 'colores', 2, '/symbols/blanco.svg'),
  ('hoy', 'Hoy', 'Today', 'tiempo', 3, '/symbols/hoy.svg'),
  ('manana', 'Mañana', 'Tomorrow', 'tiempo', 2, '/symbols/manana.svg'),
  ('ayer', 'Ayer', 'Yesterday', 'tiempo', 2, '/symbols/ayer.svg'),
  ('ahora', 'Ahora', 'Now', 'tiempo', 3, '/symbols/ahora.svg'),
  ('despues', 'Después', 'Later', 'tiempo', 3, 'https://api.arasaac.org/api/pictograms/32749?download=false'),
  ('antes', 'Antes', 'Before', 'tiempo', 2, '/symbols/antes.svg'),
  ('algo', 'Algo', 'Something', 'pronombres', 3, 'https://api.arasaac.org/api/pictograms/38768?download=false'),
  ('alguien', 'Alguien', 'Someone', 'pronombres', 2, 'https://api.arasaac.org/api/pictograms/37779?download=false'),
  ('nadie', 'Nadie', 'Nobody', 'pronombres', 2, 'https://api.arasaac.org/api/pictograms/11314?download=false')
ON CONFLICT (id) DO UPDATE SET
  spanish = EXCLUDED.spanish,
  english = EXCLUDED.english,
  category = EXCLUDED.category,
  frequency = EXCLUDED.frequency,
  symbol_url = EXCLUDED.symbol_url;

-- Verification queries
SELECT 'Total words:' as metric, COUNT(*) as value FROM public.words
UNION ALL
SELECT 'Words with symbols:', COUNT(*) FROM public.words WHERE symbol_url IS NOT NULL AND symbol_url != ''
UNION ALL
SELECT 'Words with local SVG:', COUNT(*) FROM public.words WHERE symbol_url LIKE '/symbols/%';
